### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by Noob-A** [ZaWaTeam/web-cms-project#36]
```py
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 3177, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\web-cms-project\test.py", line 4, in <module>
    user = user_manager.create_super_user('asdassaddasd', 'email', 'aefnjifenk')
  File "C:\Users\user\PycharmProjects\web-cms-project\core\managers\auth\user.py", line 59, in create_super_user
    create_permission = self.permission_manager.create_permission(
  File "C:\Users\user\PycharmProjects\web-cms-project\core\managers\auth\permissions.py", line 38, in create_permission
    create_permission = database.create_permission(
  File "C:\Users\user\PycharmProjects\web-cms-project\core\database\crud\users.py", line 89, in create_permission
    query = Permissions.get_or_create(
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 6555, in get_or_create
    return query.get(), False
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 6970, in get
    return clone.execute(database)[0]
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 1918, in inner
    return method(self, database, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 1989, in execute
    return self._execute(database)
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 2162, in _execute
    cursor = database.execute(self)
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 3190, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 3184, in execute_sql
    self.commit()
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\PycharmProjects\web-cms-project\venv\lib\site-packages\peewee.py", line 3177, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: permissions

Process finished with exit code 1
```

**Comment by Noob-A** [comment]
таблица не создана
